### ISSUE TITLE
@conda-forge-admin please rerender

### ISSUE THREAD

**Issue by traversaro** [conda-forge/librealsense-feedstock#30]
### Additional comment:

This is because the cuda aarch64 migration is failing with a re-rendering related error.

**Comment by traversaro** [comment]
This is strange, the re-rendering did nothing but the bot error is:
~~~
librealsense (0) Error: bot error ([bot CI job](https://github.com/regro/cf-scripts/actions/runs/4289084496)): main: Traceback (most recent call last): File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 1171, in _run_migrator migrator_uid, pr_json = run( File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py", line 280, in run eval_cmd( File "/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/utils.py", line 340, in eval_cmd c.check_returncode() File "/usr/share/miniconda3/envs/test/lib/python3.9/subprocess.py", line 460, in check_returncode raise CalledProcessError(self.returncode, self.args, self.stdout, subprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.
~~~

**Comment by traversaro** [comment]
Error:
~~~
2023-02-28T05:01:28.0011125Z 2023-02-28 05:01:28,000 INFO     conda_forge_tick.auto_tick || MIGRATIONYAML-cuda_112_ppc64le_aarch64 IS MIGRATING librealsense:main
2023-02-28T05:01:30.2960237Z error: pathspec 'rebuild-cuda_112_ppc64le_aarch64-0-1_hbe1123' did not match any file(s) known to git
2023-02-28T05:01:30.4635587Z 2023-02-28 05:01:30,463 INFO     conda_forge_tick.migrators.cross_compile || new conda-forge.yml for librealsense:={'build_platform': {'linux_aarch64': 'linux_64', 'linux_ppc64le': 'linux_64', 'osx_arm64': 'osx_64'}, 'conda_build': {'pkg_format': '2'}, 'conda_forge_output_validation': True, 'github': {'branch_name': 'main', 'tooling_branch_name': 'main'}, 'provider': {'linux_aarch64': 'azure', 'linux_ppc64le': 'azure'}, 'test': 'native_and_emulated'}
2023-02-28T05:01:30.7015744Z 2023-02-28 05:01:30,699 INFO     conda_forge_tick.auto_tick || Rerendering the feedstock
2023-02-28T05:01:35.8304720Z INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2023.02.28.00.25.39
2023-02-28T05:01:36.5926079Z INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmpd1ed84p6
2023-02-28T05:01:37.0715560Z INFO:conda_smithy.configure_feedstock:README rendering is skipped
2023-02-28T05:01:37.0716432Z INFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped
2023-02-28T05:01:37.4235860Z INFO:conda_smithy.configure_feedstock:cuda_112_ppc64le_aarch64.yaml from feedstock is ignored and upstream version is used
2023-02-28T05:01:37.4852627Z Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
2023-02-28T05:01:37.4853744Z WARNING:conda_build.config:Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
2023-02-28T05:01:37.4854895Z Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
2023-02-28T05:01:37.4855830Z WARNING:conda_build.config:Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
2023-02-28T05:01:37.4862691Z No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
2023-02-28T05:01:37.4863281Z WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
2023-02-28T05:01:37.5296884Z INFO:conda_build.variants:Adding in variants from internal_defaults
2023-02-28T05:01:37.5297352Z INFO:conda_build.variants:Adding in variants from /tmp/tmpd1ed84p6/conda_build_config.yaml
2023-02-28T05:01:37.5340991Z INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpd1ed84p6/share/conda-forge/migrations/cuda_112_ppc64le_aarch64.yaml
2023-02-28T05:01:37.7417372Z INFO:conda_build.variants:Adding in variants from argument_variants
2023-02-28T05:01:51.8049173Z INFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmpd1ed84p6/share/conda-forge/migrations/cuda_112_ppc64le_aarch64.yaml
2023-02-28T05:01:51.8063658Z Traceback (most recent call last):
2023-02-28T05:01:51.8064353Z   File "/usr/share/miniconda3/envs/test/bin/conda-smithy", line 10, in <module>
2023-02-28T05:01:51.8064814Z     sys.exit(main())
2023-02-28T05:01:51.8065439Z   File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/conda_smithy/cli.py", line 669, in main
2023-02-28T05:01:51.8065936Z     args.subcommand_func(args)
2023-02-28T05:01:51.8066541Z   File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/conda_smithy/cli.py", line 485, in __call__
2023-02-28T05:01:51.8067044Z     self._call(args, tmpdir)
2023-02-28T05:01:51.8067673Z   File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/conda_smithy/cli.py", line 490, in _call
2023-02-28T05:01:51.8068148Z     configure_feedstock.main(
2023-02-28T05:01:51.8068830Z   File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 2318, in main
2023-02-28T05:01:51.8070077Z     render_azure(env, config, forge_dir, return_metadata=True)
2023-02-28T05:01:51.8070813Z   File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 1412, in render_azure
2023-02-28T05:01:51.8071904Z     return _render_ci_provider(
2023-02-28T05:01:51.8072624Z   File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 662, in _render_ci_provider
2023-02-28T05:01:51.8073215Z     migrated_combined_variant_spec = migrate_combined_spec(
2023-02-28T05:01:51.8074288Z   File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 595, in migrate_combined_spec
2023-02-28T05:01:51.8074864Z     combined_spec = variant_add(combined_spec, migration)
2023-02-28T05:01:51.8075560Z   File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/conda_smithy/variant_algebra.py", line 239, in variant_add
2023-02-28T05:01:51.8078171Z     return VARIANT_OP[operation](v1, v2)
2023-02-28T05:01:51.8078904Z   File "/usr/share/miniconda3/envs/test/lib/python3.9/site-packages/conda_smithy/variant_algebra.py", line 168, in op_variant_key_add
2023-02-28T05:01:51.8079467Z     new_value[new_key_position] = v2[key][pkey_ind]
2023-02-28T05:01:51.8079895Z KeyError: 'docker_image'
~~~

**Comment by traversaro** [comment]
From https://github.com/conda-forge/nvcc-feedstock/issues/95 it seems that cross-compilation for CUDA is still not supported, so probably we can just switch to emulation for now to support cuda on aarch64 .

**Comment by traversaro** [comment]
@conda-forge-admin please rerender
